// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/Version.proto

#include "common/Version.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

static const ::_pb::EnumDescriptor* file_level_enum_descriptors_common_2fVersion_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_common_2fVersion_2eproto = nullptr;
const uint32_t TableStruct_common_2fVersion_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_common_2fVersion_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024common/Version.proto*\207\002\n\007Version\022\031\n\024DA"
  "TAFED_RELEASE_YEAR\020\351\017\022\031\n\025DATAFED_RELEASE"
  "_MONTH\020\006\022\027\n\023DATAFED_RELEASE_DAY\020\013\022\030\n\024DAT"
  "AFED_RELEASE_HOUR\020\016\022\032\n\026DATAFED_RELEASE_M"
  "INUTE\020\001\022%\n!DATAFED_COMMON_PROTOCOL_API_M"
  "AJOR\020\001\022%\n!DATAFED_COMMON_PROTOCOL_API_MI"
  "NOR\020\001\022%\n!DATAFED_COMMON_PROTOCOL_API_PAT"
  "CH\020\000\032\002\020\001"
  ;
static ::_pbi::once_flag descriptor_table_common_2fVersion_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_common_2fVersion_2eproto = {
    false, false, 288, descriptor_table_protodef_common_2fVersion_2eproto,
    "common/Version.proto",
    &descriptor_table_common_2fVersion_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_common_2fVersion_2eproto::offsets,
    nullptr, file_level_enum_descriptors_common_2fVersion_2eproto,
    file_level_service_descriptors_common_2fVersion_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_common_2fVersion_2eproto_getter() {
  return &descriptor_table_common_2fVersion_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_common_2fVersion_2eproto(&descriptor_table_common_2fVersion_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Version_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_common_2fVersion_2eproto);
  return file_level_enum_descriptors_common_2fVersion_2eproto[0];
}
bool Version_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 6:
    case 11:
    case 14:
    case 2025:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
