// #include "repo-server-rs/src/ffi/repo.rs.h"  // generated by cxx; defines VersionInfo
// #include "repo_bridge.hpp"

// #include "RepoServer.hpp"
// #include "Config.hpp"

// #include <memory>
// #include <thread>
// #include <atomic>
// #include <stdexcept>

// namespace {
// std::unique_ptr<SDMS::Repo::Server> g_server;
// std::thread                          g_thread;
// std::atomic<bool>                    g_running{false};
// }

// namespace RepoBridge {

// void server_start(rust::Str config_path) {
//   if (g_running.load()) return;

//   // Load config and create server
//   auto& cfg = SDMS::Repo::Config::getInstance();
//   cfg.loadFromFile(std::string(config_path));   // adapt if your Config API differs

//   g_server = std::make_unique<SDMS::Repo::Server>(cfg);
//   g_thread = std::thread([]{
//     g_running.store(true);
//     try {
//       g_server->run();   // blocks until stop requested
//     } catch (const std::exception& e) {
//       // If you want, log with DynaLog here
//     }
//     g_running.store(false);
//   });
// }

// void server_stop() {
//   if (!g_server) return;
//   g_server->stop();      // implement stop() in Server if needed, otherwise set a flag it checks
// }

// void server_join() {
//   if (g_thread.joinable()) g_thread.join();
//   g_server.reset();
// }

// } // namespace RepoBridge

#include "repo-server-rs/src/ffi/repo.rs.h"
#include "repo_bridge.hpp"
#include <atomic>
#include <thread>
#include <chrono>
#include <iostream>

namespace {
std::atomic<bool> g_running{false};
std::thread g_thr;
void run_loop() {
  while (g_running.load()) std::this_thread::sleep_for(std::chrono::milliseconds(200));
}
}

namespace ServerBridge {
void server_start(rust::Str config_path) {
  if (g_running.exchange(true)) return;
  std::cerr << "[repo-server] start: " << std::string(config_path) << "\n";
  g_thr = std::thread(run_loop);
}
void server_stop() {
  if (!g_running.exchange(false)) return;
  std::cerr << "[repo-server] stop\n";
}
void server_join() {
  if (g_thr.joinable()) g_thr.join();
}
}
