// cxx/bridge.cc
#include "bridge.hpp"

// This header is generated by cxx for your Rust bridge module.
// The -I path for it is added by cxx_build automatically.
#include "repo-server-rs/src/ffi.rs.h"

#include <common/DynaLog.hpp>
#include <memory>
#include <string>
#include <iostream>
#include <common/SocketOptions.hpp>
#include <common/ProtocolTypes.hpp>
#include <zmq.hpp>

namespace SDMS {

// Mock keys for testing - these should match your mock server
const std::string MOCK_PUBLIC_KEY = "4X1hKiU5pdwdk.s7&=Q2(b1]p!^Nj=Dnk2&7vh@f";
const std::string MOCK_PRIVATE_KEY = "G1DpacgVoCcRmLYQ6PA8:Q$]/w5SE*Qm?)}L!@Gv";

void repo_set_log_defaults() {
  std::cerr << "[INFO] Setting log defaults" << std::endl;
  std::cerr << "[INFO] Mock credentials loaded for testing:" << std::endl;
  std::cerr << "[INFO] Public Key: " << MOCK_PUBLIC_KEY << std::endl;
  std::cerr << "[INFO] Private Key: " << MOCK_PRIVATE_KEY << std::endl;
  // TODO: Implement proper logging initialization when global_logger is available
}

void repo_log_info(rust::Str thread_name, rust::Str correlation_id, std::uint64_t thread_id, rust::Str msg) {
  // Convert rust::Str to std::string safely.
  std::string thread_name_str(thread_name.data(), thread_name.size());
  std::string correlation_id_str(correlation_id.data(), correlation_id.size());
  std::string msg_str(msg.data(), msg.size());
  
  // TODO: Implement proper logging when global_logger is available
  // For now, just print to stderr as a simple fallback
  std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] " << msg_str << std::endl;
}

std::unique_ptr<ICommunicator> make_client(
    rust::Str host,
    rust::Str endpoint,
    ICredentials const& creds,
    std::uint32_t sid,
    std::int64_t poll_timeout_ms) {
  // TODO: Implement actual client creation logic
  // For now, return a null pointer as a placeholder
  return std::unique_ptr<ICommunicator>{};
}




bool check_core_server_version(rust::Str core_server_address, rust::Str thread_name, rust::Str correlation_id, std::uint64_t thread_id) {
  try {
    // Convert rust::Str to std::string
    std::string server_addr(core_server_address.data(), core_server_address.size());
    std::string thread_name_str(thread_name.data(), thread_name.size());
    std::string correlation_id_str(correlation_id.data(), correlation_id.size());
    
    // Log the attempt
    std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Checking core server version at " << server_addr << std::endl;
    
    // Parse the server address to extract host and port
    std::string host;
    uint16_t port = 0;
    
    // Simple parsing for tcp://host:port format
    if (server_addr.substr(0, 6) == "tcp://") {
      size_t colon_pos = server_addr.find(':', 6);
      if (colon_pos != std::string::npos) {
        host = server_addr.substr(6, colon_pos - 6);
        port = static_cast<uint16_t>(std::stoi(server_addr.substr(colon_pos + 1)));
      } else {
        host = server_addr.substr(6);
      }
    } else {
      host = server_addr;
    }
    
    std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Parsed address - Host: " << host << ", Port: " << port << std::endl;
    
    // Use common library socket options for proper configuration
    SocketOptions socket_options;
    socket_options.scheme = URIScheme::TCP;
    socket_options.class_type = SocketClassType::CLIENT;
    socket_options.direction_type = SocketDirectionalityType::BIDIRECTIONAL;
    socket_options.communication_type = SocketCommunicationType::ASYNCHRONOUS;
    socket_options.connection_life = SocketConnectionLife::PERSISTENT;
    socket_options.connection_security = SocketConnectionSecurity::INSECURE;
    socket_options.protocol_type = ProtocolType::ZQTP;
    socket_options.host = host;
    socket_options.port = port;
    socket_options.local_id = "repo-server-version-check";
    
    // Print the keys being used for authentication
    std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Using mock credentials for testing:" << std::endl;
    std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Public Key: " << MOCK_PUBLIC_KEY << std::endl;
    std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Private Key: " << MOCK_PRIVATE_KEY << std::endl;
    
    std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Using common library socket configuration for ZeroMQ connection..." << std::endl;
    
    // Test basic ZeroMQ connection using common library configuration
    try {
      // Create ZeroMQ context
      zmq::context_t context(1);
      
      // Create socket (using ZMQ_REQ for request-reply pattern)
      zmq::socket_t socket(context, ZMQ_REQ);
      
      // Set timeout based on common library configuration
      socket.set(zmq::sockopt::rcvtimeo, 5000); // 5 second timeout
      socket.set(zmq::sockopt::sndtimeo, 5000); // 5 second timeout
      
      // Connect to server using common library parsed address
      std::string connect_string = "tcp://" + host + ":" + std::to_string(port);
      std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Connecting to " << connect_string << std::endl;
      
      socket.connect(connect_string);
      std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Connected successfully" << std::endl;
      
      // Send a version request that your mock server expects
      // This should match the protocol your mock server is using
      std::string request = "VERSION_REQUEST";
      zmq::message_t zmq_request(request.data(), request.size());
      
      std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Sending version request..." << std::endl;
      socket.send(zmq_request, zmq::send_flags::none);
      
      // Try to receive response
      zmq::message_t response;
      auto recv_result = socket.recv(response, zmq::recv_flags::none);
      
      if (recv_result) {
        std::string response_str(static_cast<char*>(response.data()), response.size());
        std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Received response: " << response_str << std::endl;
        return true;
      } else {
        std::cerr << "[WARN] [" << thread_name_str << ":" << thread_id << "] No response received" << std::endl;
        return false;
      }
      
    } catch (const zmq::error_t& e) {
      std::cerr << "[ERROR] [" << thread_name_str << ":" << thread_id << "] ZeroMQ error: " << e.what() << std::endl;
      return false;
    }
    
  } catch (const std::exception& e) {
    std::cerr << "[ERROR] [" << thread_name.data() << ":" << thread_id << "] Version check failed: " << e.what() << std::endl;
    return false;
  }
}

} // namespace SDMS
