// cxx/bridge.cc
#include "bridge.hpp"

// This header is generated by cxx for your Rust bridge module.
// The -I path for it is added by cxx_build automatically.
#include "repo-server-rs/src/ffi.rs.h"

// DataFed common includes
#include <common/DynaLog.hpp>
#include <common/ICommunicator.hpp>
#include <common/ICredentials.hpp>
#include <common/IMessage.hpp>
#include <common/MessageFactory.hpp>
#include <common/CommunicatorFactory.hpp>
#include <common/SocketOptions.hpp>
#include <common/ProtoBufMap.hpp>
#include <common/ProtocolTypes.hpp>

// Third party includes
#include <memory>
#include <string>
#include <iostream>
#include <sstream>
#include <zmq.hpp>

namespace SDMS {

// Mock keys for testing - these should match your mock server
const std::string MOCK_PUBLIC_KEY = "4X1hKiU5pdwdk.s7&=Q2(b1]p!^Nj=Dnk2&7vh@f";
const std::string MOCK_PRIVATE_KEY = "G1DpacgVoCcRmLYQ6PA8:Q$]/w5SE*Qm?)}L!@Gv";

// Global instances for protobuf management
static std::unique_ptr<ProtoBufMap> g_proto_map = nullptr;
static std::unique_ptr<MessageFactory> g_message_factory = nullptr;

// Mock credentials implementation
class MockCredentials : public ICredentials {
private:
    std::string m_public_key;
    std::string m_private_key;

public:
    MockCredentials(const std::string& public_key, const std::string& private_key)
        : m_public_key(public_key), m_private_key(private_key) {}

    ProtocolType getType() const noexcept override {
        return ProtocolType::ZQTP;
    }

    std::string get(CredentialType type) const override {
        switch (type) {
            case CredentialType::PUBLIC_KEY:
                return m_public_key;
            case CredentialType::PRIVATE_KEY:
                return m_private_key;
            case CredentialType::SERVER_KEY:
                return m_public_key; // For testing, use public key as server key
            default:
                return "";
        }
    }

    bool has(CredentialType type) const noexcept override {
        return type == CredentialType::PUBLIC_KEY || 
               type == CredentialType::PRIVATE_KEY || 
               type == CredentialType::SERVER_KEY;
    }
};

void repo_set_log_defaults() {
    std::cerr << "[INFO] Setting log defaults" << std::endl;
    std::cerr << "[INFO] Mock credentials loaded for testing:" << std::endl;
    std::cerr << "[INFO] Public Key: " << MOCK_PUBLIC_KEY << std::endl;
    std::cerr << "[INFO] Private Key: " << MOCK_PRIVATE_KEY << std::endl;
    
    // Initialize global protobuf instances
    if (!g_proto_map) {
        g_proto_map = std::make_unique<ProtoBufMap>();
    }
    if (!g_message_factory) {
        g_message_factory = std::make_unique<MessageFactory>();
    }
}

void repo_log_info(rust::Str thread_name, rust::Str correlation_id, std::uint64_t thread_id, rust::Str msg) {
    // Convert rust::Str to std::string safely.
    std::string thread_name_str(thread_name.data(), thread_name.size());
    std::string correlation_id_str(correlation_id.data(), correlation_id.size());
    std::string msg_str(msg.data(), msg.size());
    
    // TODO: Implement proper logging when global_logger is available
    // For now, just print to stderr as a simple fallback
    std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] " << msg_str << std::endl;
}

std::unique_ptr<ICommunicator> make_client(
    rust::Str host,
    rust::Str endpoint,
    std::uint32_t sid,
    std::int64_t poll_timeout_ms) {
    
    try {
        // Convert rust::Str to std::string
        std::string host_str(host.data(), host.size());
        std::string endpoint_str(endpoint.data(), endpoint.size());
        
        // Create socket options
        SocketOptions socket_options;
        socket_options.scheme = URIScheme::TCP;
        socket_options.class_type = SocketClassType::CLIENT;
        socket_options.direction_type = SocketDirectionalityType::BIDIRECTIONAL;
        socket_options.communication_type = SocketCommunicationType::ASYNCHRONOUS;
        socket_options.connection_life = SocketConnectionLife::PERSISTENT;
        socket_options.connection_security = SocketConnectionSecurity::INSECURE;
        socket_options.protocol_type = ProtocolType::ZQTP;
        socket_options.host = host_str;
        
        // Parse port from endpoint if provided
        if (!endpoint_str.empty()) {
            try {
                socket_options.port = static_cast<uint16_t>(std::stoi(endpoint_str));
            } catch (const std::exception& e) {
                std::cerr << "[WARN] Could not parse port from endpoint: " << endpoint_str << std::endl;
            }
        }
        
        socket_options.local_id = "repo-server-client-" + std::to_string(sid);
        
        // Create log context
        LogContext log_context;
        log_context.thread_name = "repo-client";
        log_context.correlation_id = "client-" + std::to_string(sid);
        log_context.thread_id = sid;
        
        // Create mock credentials for testing
        MockCredentials credentials(MOCK_PUBLIC_KEY, MOCK_PRIVATE_KEY);
        
        // Create communicator factory and communicator
        CommunicatorFactory factory(log_context);
        auto communicator = factory.create(socket_options, credentials, 
                                         static_cast<uint32_t>(poll_timeout_ms), 
                                         poll_timeout_ms);
        
        if (!communicator) {
            std::cerr << "[ERROR] Failed to create communicator" << std::endl;
            return nullptr;
        }
        
        std::cerr << "[INFO] Created communicator with ID: " << communicator->id() 
                  << " for address: " << communicator->address() << std::endl;
        
        return communicator;
        
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to create client: " << e.what() << std::endl;
        return nullptr;
    }
}

std::unique_ptr<IMessage> create_version_request() {
    try {
        if (!g_message_factory) {
            std::cerr << "[ERROR] Message factory not initialized" << std::endl;
            return nullptr;
        }
        
        // Create a simple string message for version request
        auto message = g_message_factory->create(MessageType::STRING);
        if (!message) {
            std::cerr << "[ERROR] Failed to create message envelope" << std::endl;
            return nullptr;
        }
        
        // Set the string payload
        message->setPayload("VERSION_REQUEST");
        
        // Set message attributes
        message->set(MessageAttribute::STATE, MessageState::REQUEST);
        
        return message;
        
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to create version request: " << e.what() << std::endl;
        return nullptr;
    }
}

std::unique_ptr<IMessage> create_version_reply() {
    try {
        if (!g_message_factory) {
            std::cerr << "[ERROR] Message factory not initialized" << std::endl;
            return nullptr;
        }
        
        // Create a simple string message for version reply
        auto message = g_message_factory->create(MessageType::STRING);
        if (!message) {
            std::cerr << "[ERROR] Failed to create message envelope" << std::endl;
            return nullptr;
        }
        
        // Set the string payload with version info
        std::string version_info = R"({
            "release_year": 2024,
            "release_month": 12,
            "release_day": 1,
            "api_major": 1,
            "api_minor": 0,
            "api_patch": 0,
            "component_major": 1,
            "component_minor": 0,
            "component_patch": 0
        })";
        
        message->setPayload(version_info);
        
        // Set message attributes
        message->set(MessageAttribute::STATE, MessageState::RESPONSE);
        
        return message;
        
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to create version reply: " << e.what() << std::endl;
        return nullptr;
    }
}

rust::String serialize_message_to_json(IMessage const& message) {
    try {
        // For now, just return a simple JSON representation
        // In a full implementation, you would properly serialize the message
        return rust::String("{\"type\": \"message\", \"status\": \"serialized\"}");
        
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to serialize message to JSON: " << e.what() << std::endl;
        return rust::String("{}");
    }
}

std::unique_ptr<IMessage> deserialize_message_from_json(rust::Str json_str) {
    try {
        if (!g_message_factory) {
            std::cerr << "[ERROR] Message factory not initialized" << std::endl;
            return nullptr;
        }
        
        std::string json_string(json_str.data(), json_str.size());
        
        // Create a simple string message
        auto message = g_message_factory->create(MessageType::STRING);
        if (!message) {
            std::cerr << "[ERROR] Failed to create message envelope" << std::endl;
            return nullptr;
        }
        
        message->setPayload(json_string);
        message->set(MessageAttribute::STATE, MessageState::REQUEST);
        
        return message;
        
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to deserialize message from JSON: " << e.what() << std::endl;
        return nullptr;
    }
}

bool send_message(std::unique_ptr<ICommunicator>& communicator, std::unique_ptr<IMessage>& message) {
    try {
        if (!communicator || !message) {
            std::cerr << "[ERROR] Null communicator or message" << std::endl;
            return false;
        }
        communicator->send(*message);
        return true;
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to send message: " << e.what() << std::endl;
        return false;
    }
}

std::unique_ptr<IMessage> receive_message(std::unique_ptr<ICommunicator>& communicator) {
    try {
        if (!communicator) {
            std::cerr << "[ERROR] Null communicator" << std::endl;
            return nullptr;
        }
        auto response = communicator->receive(MessageType::STRING);
        if (response.error) {
            std::cerr << "[ERROR] Receive error: " << response.error_msg << std::endl;
            return nullptr;
        }
        
        if (response.time_out) {
            std::cerr << "[WARN] Receive timeout" << std::endl;
            return nullptr;
        }
        
        return std::move(response.message);
        
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] Failed to receive message: " << e.what() << std::endl;
        return nullptr;
    }
}

bool check_core_server_version(rust::Str core_server_address, rust::Str thread_name, rust::Str correlation_id, std::uint64_t thread_id) {
    try {
        // Convert rust::Str to std::string
        std::string server_addr(core_server_address.data(), core_server_address.size());
        std::string thread_name_str(thread_name.data(), thread_name.size());
        std::string correlation_id_str(correlation_id.data(), correlation_id.size());
        
        // Log the attempt
        std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Checking core server version at " << server_addr << std::endl;
        
        // Parse the server address to extract host and port
        std::string host;
        uint16_t port = 9998; // Default DataFed port
        
        // Simple parsing for tcp://host:port format
        if (server_addr.substr(0, 6) == "tcp://") {
            size_t colon_pos = server_addr.find(':', 6);
            if (colon_pos != std::string::npos) {
                host = server_addr.substr(6, colon_pos - 6);
                port = static_cast<uint16_t>(std::stoi(server_addr.substr(colon_pos + 1)));
            } else {
                host = server_addr.substr(6);
            }
        } else {
            host = server_addr;
        }
        
        std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Parsed address - Host: " << host << ", Port: " << port << std::endl;
        
        // Create mock credentials
        MockCredentials credentials(MOCK_PUBLIC_KEY, MOCK_PRIVATE_KEY);
        
        // Create client communicator
        auto communicator = make_client(host, std::to_string(port), thread_id, 5000);
        if (!communicator) {
            std::cerr << "[ERROR] [" << thread_name_str << ":" << thread_id << "] Failed to create communicator" << std::endl;
            return false;
        }
        
        // Create version request
        auto version_request = create_version_request();
        if (!version_request) {
            std::cerr << "[ERROR] [" << thread_name_str << ":" << thread_id << "] Failed to create version request" << std::endl;
            return false;
        }
        
        // Send version request
        std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Sending version request..." << std::endl;
        if (!send_message(communicator, version_request)) {
            std::cerr << "[ERROR] [" << thread_name_str << ":" << thread_id << "] Failed to send version request" << std::endl;
            return false;
        }
        
        // Receive response
        auto response = receive_message(communicator);
        if (!response) {
            std::cerr << "[ERROR] [" << thread_name_str << ":" << thread_id << "] Failed to receive version response" << std::endl;
            return false;
        }
        
        // Log the response
        std::cerr << "[INFO] [" << thread_name_str << ":" << thread_id << "] Received version response successfully" << std::endl;
        
        return true;
        
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] [" << thread_name.data() << ":" << thread_id << "] Version check failed: " << e.what() << std::endl;
        return false;
    }
}

} // namespace SDMS
