[package]
name = "repo-server-rs"
version = "0.1.0"
edition = "2024"

[profile.release]
# Optimize for compatibility and reduce glibc dependency
lto = true
codegen-units = 1
strip = true



[dependencies]
ctrlc = "3.4.7"
cxx = "1"
serde = { version = "1", features = ["derive"] }
toml  = "0.8"
sodiumoxide = "0.2.7"
base64 = "0.21"

[build-dependencies]
cxx-build = "1"
