# Address of the DataFed core (the server will connect to it)
core_server = "tcp://128.219.184.185:9998"

# Directory that contains the key files used by the sample server code:
#   datafed-repo-key.pub
#   datafed-repo-key.priv
#   datafed-core-key.pub
cred_dir = "/opt/datafed/keys/"

# Repo server listen port
port = 9000

# Request timeout (ms)
timeout = 20000

# Number of worker threads to serve client requests
num_req_worker_threads = 4

# Optional
globus_collection_path = ""
